name: eshop
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8


  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0

  bloc: ^8.1.2
  flutter_bloc: ^8.0.1
  get_it: ^7.6.0

  http: ^0.13.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1

  
  oktoast: ^3.3.1
  flutter_snake_navigationbar: ^0.6.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  flutter_easyloading: ^3.0.5
  sizer: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.4


flutter:


  uses-material-design: true

  assets:
    - assets/navbar_icons/
    - assets/status_image/
    - assets/dev/
    - assets/other_images/
    - assets/icons/